export const ADD_POST = "ADD_POST";
export const GET_POSTS = "GET_POSTS";
export const FETCH_POSTS = "FETCH_POSTS";
export const FETCH_POSTS_FULFIELD = "FETCH_POSTS_FULFIELD";
export const FETCH_POSTS_REJECTED = "FETCH_POSTS_REJECTED";
export const FETCH_POSTS_PENDING = "FETCH_POSTS_PENDING";
