export const ADD_USER = "ADD_USER";
export const GET_USERS = "GET_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FULFIELD = "FETCH_USERS_FULFIELD";
export const FETCH_USERS_REJECTED = "FETCH_USERS_REJECTED";
export const FETCH_USERS_PENDING = "FETCH_USERS_PENDING";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FULFIELD = "FETCH_USER_FULFIELD";
export const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";
export const FETCH_USER_PENDING = "FETCH_USER_PENDING";
